language: node.js
node_js:
  - 10

script: node_modules/karma/bin/karma start test/karma.conf.js --single-run

before_install:
  - npm install -g @angular/cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: npm install

branches:
  only:
    - master

deploy:
  provider: heroku
  app: roxy-notes
  api_key:
    secure: "d5b49d95-1170-4817-afdc-613ba1fd6b0a"
