sudo: false
language: node.js
node_js:
- 10
before_install:
- npm install -g @angular/cli
install: npm install
cache:
  directories:
  - node_modules
dist: trusty
branches:
  only:
  - master
deploy:
  provider: heroku
  app: roxy-notes
  api_key:
    secure: JdvSOyGaLF6RSHVUEHR2b5er/+43zlv5CkmmFklOuwZuKigXChkFZWNENGQK9UmzHdx3KvkxJZCu7FJxFSqJJ5ZN8Q2VZtxrtvYJR7G9EPNM6ClIwaU8nZrr80fFoHEjWsEb9bXMxCoL4PI+wvwxahTIqHj6zaZqXGGC2gkBgUcloWoeGChGY0V9vUfySrJnhdQSRMZAtdbj/rN5AHLePPYL6Tb66sA3jLYL8McBSHS1vsPuKyBnmbRo735cx9VYh2G7McoyBrht/0w10C+tySjqzxYURKaXu1B8tdoMTzvhMh7uOg5tIhoSGMCiVJlcHDSqrFIWBdgeW4FK5t4v/MZ/0JNhvB7X2J7PC79zOgpZZgFSExrLNZCHiN/wdPAYG5r6+Awwkq9J7vv9odd2Y2jDTv1HupLC9uwyjTd0IcwgjVqsKGMmBWBKZFtSwhBqYQ2OIOfHEQkjksIxO1ziioQ/fmcYx3dsflyYOKvp9EajGuJGrS03VvMZQhKtuzaFg1LfWYnQJWmIIoDh1T1nNmj2iVHhjAY2TFiB7vu6k6V1HKUFtX1GcnA2L9QYw5k3qa7EetFv+XWcz2mT3qDl7t5dXMwdl5EnmslzhZoCYAh7avRjViGFnwvAybOA0w4w56qPxAgsfS/9BhWmIjsjrmG7DxaBPKY+/N1ealQ/mn0=
