language: node.js
node_js:
- 12
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: heroku
  app: second-test-bla-bla
  api_key:
    secure: 346d532d-4ae9-4a16-a965-b26f4c2f8294
